language: scala
scala:
   - 2.11.7
jdk:
   - oraclejdk8
deploy:
  provider: opsworks
  access-key-id: AKIAJNN5LAFE7636SLCQ
  secret-access-key: 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
  app-id: 8f6e1a3c-5ed0-4d20-bbf3-56cb485e0217


